const PLAYLIST='https://iptv-org.github.io/iptv/countries/us.m3u';
const FALLBACK=[
{name:'48 Hours',url:'https://dai.google.com/linear/hls/event/JUr94WL2QAiVpGNHY5n5dA/master.m3u8',logo:'',group:'Movies'},
{name:'beIN SPORTS XTRA',url:'https://bein-xtra-bein.amagi.tv/playlist.m3u8',logo:'https://i.ibb.co/HT49GPmB/XTRA-2.png',group:'Sports'},
{name:'BabyFirst',url:'https://cdn.fast.jwp.services/v1/channel/1_jB6940Ei_TvhvIHDL/manifest.m3u8',logo:'https://i.imgur.com/WxLHBwu.png',group:'Kids'},
{name:'Baby Shark TV',url:'https://newidco-babysharktv-1-us.roku.wurl.tv/playlist.m3u8',logo:'https://i.imgur.com/SbBKr8L.png',group:'Kids'},
{name:'Black News Channel',url:'https://blacknewschannel-xumo-us.amagi.tv/playlist.m3u8',logo:'https://i.imgur.com/oX5oR4d.png',group:'News'},
{name:'BEK TV Sports West',url:'https://cdn3.wowza.com/5/ZWQ1K2NYTmpFbGsr/BEK-WOWZA-1/smil:BEKPRIMEW.smil/playlist.m3u8',logo:'https://i.imgur.com/1l3t5jd.png',group:'Sports'},
{name:'Antiques Roadshow PBS',url:'https://amg00953-pbsusa-antiroadshow-xumo-x6ud5.amagi.tv/playlist.m3u8',logo:'https://i.imgur.com/U9CYaok.png',group:'Series'},
{name:'Artflix Movie Classics',url:'https://amogonetworx-artflix-1-nl.samsung.wurl.tv/playlist.m3u8',logo:'https://i.imgur.com/5pOZQB4.png',group:'Movies'},
{name:'30A Golf Kingdom',url:'https://30a-tv.com/feeds/vidaa/golf.m3u8',logo:'',group:'Sports'},
{name:'30A TV Classic Movies',url:'https://30a-tv.com/feeds/pzaz/30atvmovies.m3u8',logo:'',group:'Movies'}
];
const GROUPS=['All','Popular','Local/News','Sports','Kids','Movies','Comedy','Weather','Texas','Music'];
const video=document.querySelector('#video'),list=document.querySelector('#list'),groups=document.querySelector('#groups'),search=document.querySelector('#search'),status=document.querySelector('#status'),nameEl=document.querySelector('#name'),details=document.querySelector('#details'),playBtn=document.querySelector('#play'),watch=document.querySelector('.watch');
let items=[],shown=[],idx=0,active='Popular',hls=null,touchX=0,loaded=false,skipTimer=null;
const esc=(s='')=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function category(n,g=''){const s=(n+' '+g).toLowerCase();if(/texas|dallas|fort worth|dfw|austin|houston|san antonio/.test(s))return'Texas';if(/weather|accuweather/.test(s))return'Weather';if(/sport|nfl|nba|mlb|nhl|soccer|golf|racing|mma|ufc|billiard/.test(s))return'Sports';if(/kid|cartoon|baby|family|junior/.test(s))return'Kids';if(/movie|cinema|film|classic|western|action|horror/.test(s))return'Movies';if(/comedy|sitcom|funny/.test(s))return'Comedy';if(/music|vevo|concert/.test(s))return'Music';if(/news|abc|cbs|nbc|fox|pbs|cw|c-span|local/.test(s))return'Local/News';return g||'General'}
function score(x){const s=(x.name+' '+x.rawGroup).toLowerCase();let p=0;if(/\b(abc|cbs|nbc|fox|pbs|cw)\b/.test(s))p+=80;if(/news|weather/.test(s))p+=45;if(/texas|dallas|fort worth|dfw/.test(s))p+=50;if(/sports|nfl|nba|mlb|golf|bein/.test(s))p+=35;if(/kids|movie|comedy/.test(s))p+=15;if(/geo-blocked/.test(s))p-=100;return p}
function parseM3U(text){const lines=text.split(/\r?\n/);let meta=null,out=[];for(const raw of lines){const x=raw.trim();if(x.startsWith('#EXTINF:')){const attrs={};for(const m of x.matchAll(/([\w-]+)="([^"]*)"/g))attrs[m[1]]=m[2];meta={name:(x.split(',').slice(1).join(',')||'Unknown').trim(),logo:attrs['tvg-logo']||'',rawGroup:attrs['group-title']||'',desc:attrs['tvg-name']||''}}else if(meta&&x&&!x.startsWith('#')){if(/^https:\/\//i.test(x)&&/\.m3u8(?:\?|$)/i.test(x)){meta.url=x;meta.group=category(meta.name,meta.rawGroup);meta.description=meta.desc||meta.rawGroup||meta.group;meta.score=score(meta);out.push(meta)}meta=null}}const seen=new Set();return out.filter(x=>!seen.has(x.url)&&seen.add(x.url)).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,500)}
async function load(){status.textContent='Loading US channels…';try{const r=await fetch(PLAYLIST,{cache:'no-store'});if(!r.ok)throw new Error('playlist');items=parseM3U(await r.text());if(!items.length)throw new Error('empty');status.textContent=`${items.length} US channels loaded`}catch(e){items=FALLBACK.map(x=>({...x,rawGroup:x.group,description:x.group,score:10}));status.textContent='Using verified fallback channels'}renderGroups();filter();}
function renderGroups(){groups.innerHTML=GROUPS.map(g=>`<button class="${g===active?'on':''}" data-g="${g}">${g}</button>`).join('');groups.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.g;idx=0;renderGroups();filter()})}
function filter(){const q=search.value.toLowerCase().trim();shown=items.filter(x=>{const groupOK=active==='All'||(active==='Popular'?x.score>=35:x.group===active);const qOK=!q||(x.name+' '+x.description+' '+x.group).toLowerCase().includes(q);return groupOK&&qOK});if(!shown.length&&active==='Popular'){shown=items.slice(0,120)}list.innerHTML=shown.length?shown.map((x,i)=>`<article class="channel ${i===idx?'selected':''}" data-i="${i}" tabindex="0">${x.logo?`<img src="${esc(x.logo)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.outerHTML='<div class=&quot;fallback&quot;>${esc(x.name.slice(0,2).toUpperCase())}</div>'">`:`<div class="fallback">${esc(x.name.slice(0,2).toUpperCase())}</div>`}<div><b>${esc(x.name)}</b><p>${esc(x.description||x.group)}</p></div><span class="tag">${esc(x.group)}</span></article>`).join(''):'<div class="empty">No channels found</div>';list.querySelectorAll('.channel').forEach(r=>{r.onclick=()=>select(+r.dataset.i,true);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(+r.dataset.i,true)}}});status.textContent=`${shown.length} channels`;if(shown.length){idx=Math.min(idx,shown.length-1);select(idx,false)}}
function cleanup(){clearTimeout(skipTimer);skipTimer=null;if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load()}
function select(i,start=false){if(!shown.length)return;idx=(i+shown.length)%shown.length;const c=shown[idx];localStorage.setItem('open-tv-last',c.name);nameEl.textContent=c.name;details.textContent=c.description||c.group;document.querySelectorAll('.channel').forEach((el,j)=>el.classList.toggle('selected',j===idx));if(start)playCurrent();else{video.poster=c.logo||'';playBtn.textContent='▶';status.textContent=`Ready: ${c.name}`}}
function playCurrent(){if(!shown.length)return;const c=shown[idx];cleanup();loaded=true;video.poster='';status.textContent=`Connecting: ${c.name}`;const fail=()=>{if(skipTimer)return;status.textContent='Unavailable — trying next';skipTimer=setTimeout(()=>{skipTimer=null;next(true)},900)};if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.play().then(()=>status.textContent=`LIVE · ${c.name}`).catch(fail);video.onerror=fail}else if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:20,manifestLoadingTimeOut:8000,levelLoadingTimeOut:8000,fragLoadingTimeOut:10000});hls.loadSource(c.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().then(()=>status.textContent=`LIVE · ${c.name}`).catch(fail));hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)fail()})}else{status.textContent='This browser cannot play HLS'} }
function prev(start=loaded){select(idx-1,false);if(start)playCurrent()}function next(start=loaded){select(idx+1,false);if(start)playCurrent()}
document.querySelector('#prev').onclick=()=>prev();document.querySelector('#next').onclick=()=>next();playBtn.onclick=()=>{if(!shown.length)return;if(!loaded||(!video.src&&!hls)){playCurrent();return}if(video.paused)video.play().catch(()=>playCurrent());else video.pause()};video.onplay=()=>playBtn.textContent='❚❚';video.onpause=()=>playBtn.textContent='▶';search.oninput=()=>{idx=0;filter()};document.addEventListener('keydown',e=>{if(e.target===search)return;if(e.key==='ArrowLeft'){e.preventDefault();prev()}else if(e.key==='ArrowRight'){e.preventDefault();next()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();playBtn.click()}});watch.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});watch.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>50)(dx>0?prev:next)()},{passive:true});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));load();